### PR TITLE
PHP 8.4 compatibility

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by ruudk** [comment]
@dbu could you please approve the workflow? The other error is unrelated.

**Comment by dbu** [comment]
i fixed the cs error in the 1.x branch.

oh boy, this has not been updated in a while. do you have time to investigate the setup issues? hopefully we just need to allow new versions of dependencies.

**Comment by ruudk** [comment]
PHPSpec, the gift that keeps on giving 😭 I think it should be removed, and replaced with PHPUnit.

**Comment by ruudk** [comment]
Before we do any work, wouldn't it make more sense to remove EOL PHP versions too?

**Comment by dbu** [comment]
looking how few tests we have here (and how small the component is): yes please, lets just switch to phpunit.

our policy regarding dropping EOL php versions has been to drop then when they become a nuisance, but not to just drop them when all is still fine. i guess with phpunit upgrade, it would be nice to use a recent version directly - i am fine with dropping EOL versions that hinder using a recent phpunit version.

**Comment by ruudk** [comment]
Handled in https://github.com/php-http/logger-plugin/pull/27

**Pull request closed without merging**
