### PR TITLE
Support PHP 7.1-8.0

### PR DESCRIPTION
**Pull request by GrahamCampbell**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| License         | MIT

* Drop PHP <7.1
* Use `hrtime` to avoid negative timing when the system clock changes (which can happen quite a lot - my Macbook seems to change the system clock by a few seconds more than once an hour)
* Add support for PHP 7.4 and 8.0
* Move to GitHub actions for testing

Tests pass: https://github.com/GrahamCampbell/logger-plugin/runs/866077906.

### CODE REVIEW

**Review by dbu — COMMENTED** [review]
thanks, some good cleanups :+1: 

and cool thing with hrtime, i was not aware that microtime is fragile.

the high resolution time module is not bundled with php according to https://www.php.net/manual/en/hrtime.installation.php

i think we should check if the hrtime function exist and fallback to microtime. otherwise this would be a breaking change & could prevent people from using all the other functionality of the logger plugin that does not care about timing.

**Comment by GrahamCampbell** [comment]
> the high resolution time module is not bundled with php according to https://www.php.net/manual/en/hrtime.installation.php

The `hrtime` function (https://www.php.net/manual/en/function.hrtime.php) is not the same as the hrtime extension (which provides an OOP timing library). The function is a core function added to PHP 7.3. If it is not available (if and only if the PHP version is less than 7.3), we fallback to the symfony polyfill I already required (line 18 composer.json). As far as I'm aware, it is not possible to compile PHP 7.3+ without the hrtime function. :)

**Comment by dbu** [comment]
great, thanks for the explanation. i somehow assumed the function would be part of the extension - learned something new today :-D

**Comment by GrahamCampbell** [comment]
🎉 Thanks for your super speedy reviews. :)

**Comment by dbu** [comment]
well, thanks for all the work you put into the libraries! :+1:

**Pull request merged**
