### PR TITLE
Adding time for the request

### PR DESCRIPTION
**Pull request by Nyholm**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | 
| Documentation   | if this is a new feature, link to pull request in https://github.com/php-http/documentation that adds relevant documentation
| License         | MIT

#### What's in this PR?

We should log the time it takes to make a request

If we think this is something we want Im happy to complete this PR.

#### To Do

- [x] Changelog
- [x] Tests

### CODE REVIEW

**Comment by dbu** [comment]
sounds valuable to me, lets do it!

**Comment by Nyholm** [comment]
I found this PR which I did not complete. Im not sure how I could make PHPSpec allow me to add a random integer like I did. I've searched the manual extensively but found nothing.

**Comment by nicholasruunu** [comment]
@Nyholm This is how you would handle it: https://github.com/nicholasruunu/logger-plugin/commit/b708f389998eac364bea74b254ef938dfa9403c5

But the "Received response" info calls are actually not being made when you call `handleRequest()`.

**Comment by Nyholm** [comment]
Awesome Nicholas. Thank you. Will finish this PR tonight.

**Comment by Nyholm** [comment]
The test showed that my implementation was flawed. Thanks again for helping me. 

I've used your commit and I've updated the PR. Im now ready for a review

**Review by joelwurtz — APPROVED** [review]

**Comment by joelwurtz** [comment]
Nice one. i'm also wondering if we should use `Stopwatch` in the future if present, and puts this informations in the context ?

**Comment by Nyholm** [comment]
Thank you for the review. Hm.. Isn't that done already if you use the Symfony Bundle?

**Comment by joelwurtz** [comment]
It was more using Stopwatch implementation instead of microtime if available, but not really necessary

**Pull request merged**
